gbifConfig:
  gbifApi:
    wsUrl: http://api.gbif.org
  geocode:
    wsCacheSizeMb: 128
    api:
      wsUrl: https://api.gbif.org/v1/
  extensionsAllowedForVerbatimSet:
    - http://rs.tdwg.org/ac/terms/Multimedia
    - http://data.ggbn.org/schemas/ggbn/terms/Amplification
    - http://data.ggbn.org/schemas/ggbn/terms/Cloning
    - http://data.ggbn.org/schemas/ggbn/terms/GelImage
    - http://data.ggbn.org/schemas/ggbn/terms/Loan
    - http://data.ggbn.org/schemas/ggbn/terms/MaterialSample
    - http://data.ggbn.org/schemas/ggbn/terms/Permit
    - http://data.ggbn.org/schemas/ggbn/terms/Preparation
    - http://data.ggbn.org/schemas/ggbn/terms/Preservation
    - http://rs.iobis.org/obis/terms/ExtendedMeasurementOrFact
    - http://rs.tdwg.org/chrono/terms/ChronometricAge
    - http://purl.org/germplasm/germplasmTerm#GermplasmAccession
    - http://purl.org/germplasm/germplasmTerm#MeasurementScore
    - http://purl.org/germplasm/germplasmTerm#MeasurementTrait
    - http://purl.org/germplasm/germplasmTerm#MeasurementTrial
    - http://rs.tdwg.org/dwc/terms/Identification
    - http://rs.tdwg.org/dwc/terms/Occurrence
    - http://rs.gbif.org/terms/1.0/Identifier
    - http://rs.gbif.org/terms/1.0/Image
    - http://rs.tdwg.org/dwc/terms/MeasurementOrFact
    - http://rs.gbif.org/terms/1.0/Multimedia
    - http://rs.gbif.org/terms/1.0/Reference
    - http://rs.tdwg.org/dwc/terms/ResourceRelationship
    - http://rs.gbif.org/terms/1.0/DNADerivedData
geocodeConfig:
  country:
    path: /data/pipelines-shp/political
    field: ISO_A2
    intersectBuffer:  0.135
    intersectMapping:
      CX: AU
      CC: AU
      HM: AU
      NF: AU
  eez:
    path: /data/pipelines-shp/eez
    field: ISO2
    intersectBuffer:  0.135
  stateProvince:
    path: /data/pipelines-shp/cw_state_poly
    field: FEATURE
    intersectBuffer: 0
  biome:
    path: /data/pipelines-shp/gadm0
    field: FEATURE
collectory:
  wsUrl: https://collections-test.ala.org.au/ws/
  timeoutSec: 70
  retryConfig:
    maxAttempts: 10
    initialIntervalMillis: 10000
  httpHeaders:
    Authorization: add-a-api-key-here
